# Generated by Django 4.1.1 on 2022-09-18 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, 'female'), (1, 'male')])),
                ('breed', models.CharField(max_length=64)),
                ('size', models.PositiveSmallIntegerField(choices=[(0, 'small'), (1, 'medium'), (2, 'large'), (3, 'giant')])),
                ('bio', models.TextField(null=True)),
                ('photo', models.ImageField(default='dogs/static_files/default_avatar.png', upload_to='dogs/static_files/uploads/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
