# Generated by Django 4.1.1 on 2022-09-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Wiek'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='bio',
            field=models.TextField(null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=64, verbose_name='Rasa'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(default='default_avatar.png', upload_to='dog_image', verbose_name='Zdjęcie psa'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(0, 'female'), (1, 'male')], verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(0, 'small'), (1, 'medium'), (2, 'large'), (3, 'giant')], verbose_name='Wielkość psa'),
        ),
    ]
