# Generated by Django 4.1.1 on 2022-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
