# Generated by Django 4.1.1 on 2022-09-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0004_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default_avatar.png', upload_to='user_image'),
        ),
    ]
