# Generated by Django 4.1.1 on 2022-09-26 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_dog_age_alter_dog_bio_alter_dog_breed_and_more'),
        ('dating', '0006_alter_user_address_alter_user_bio_alter_user_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('max_users', models.PositiveSmallIntegerField()),
                ('max_dogs', models.PositiveSmallIntegerField()),
                ('target_user_gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'female'), (1, 'male')], null=True)),
                ('target_user_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_dog_sex', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'female'), (1, 'male')], null=True)),
                ('target_dog_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dating.address')),
                ('participating_dogs', models.ManyToManyField(to='dogs.dog')),
                ('participating_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
