# Generated by Django 4.1.1 on 2022-09-27 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0007_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
