# Generated by Django 4.1.1 on 2022-09-27 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_dog_age_alter_dog_bio_alter_dog_breed_and_more'),
        ('dating', '0008_remove_meeting_date_time_meeting_date_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='participating_dogs',
            field=models.ManyToManyField(related_name='dogs', to='dogs.dog'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participating_users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
